config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  get 'pages/about'

  get 'pages/contact'

  resources :users, only: [:show] 

  resources :categories, only: [:show]

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true,
  				   uniqueness: true,
  				   length: { minimum: 3, maximum: 25 }
end

app/models/product.rb
class Product < ActiveRecord::Base
  if Rails.env.development?
  	has_attached_file :image, styles: { :medium => "200x"}, default_url: "./assets/images/product_image.gif"
  else
  	has_attached_file :image, styles: { :medium => "200x"}, default_url: "./assets/images/product_image.gif",
  					  :storage => :dropbox,
    				  :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    				  :path => ":style/:id_:filename"
  end

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_presence :image
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  belongs_to :user
  has_many :product_categories
  has_many :categories, through: :product_categories

  validates :categories, presence: true
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@category_products = @category.products
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @categories = Category.all
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image, category_ids: [])
    end

    def check_user
      if current_user != @product.user
        redirect_to root_url, alert: "You don't have permission to perform this action!"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@user_products = @user.products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/show.html.erb
<div class="text-center">
  <div class="row">
    <% @category_products.each do |product| %>
      <div class="col-md-8 panel panel-default col-md-offset-2">
        <div class="col-sm-4">
          <%= link_to( image_tag(product.image(:medium)), product_path(product) ) %>
        </div>
        <div class="col-sm-6">
          <p><%= link_to product.title, product_path(product) %></p>
          <% if product.categories.any? %>
            <% product.categories.each do |productCategory| %>
              <p><%= link_to productCategory.name, category_path(productCategory) %></p>
            <% end %>
          <% end %>
          <% if (user_signed_in?) && (current_user == product.user) %>
            <%= link_to 'Edit', edit_product_path(product), class: "btn btn-success" %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
          <% end %>
        </div>
        <div class="col-sm-2">
          <p><%= product.price %> fcaf</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_message.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}"%>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ShopZy', products_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Your page', user_path(current_user) %></li>
                <li><%= link_to 'Settings', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
        <li><%= link_to 'Place a product', new_product_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopzy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= render 'layouts/message' %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to ShopZy!</h1>
<p>ShopZy is a free market for easy shopping and it's for everybody.</p>

app/views/pages/contact.html.erb
<h1>Email us at support@shopzy.com</h1>

app/views/products/_form.html.erb
<div class="row">
  <%= simple_form_for(@product, html: { class: "col-md-6" }) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.input :image, as: :file %>
    </div>
    <div class="form-group">
      <%= f.association :categories,value_method: :id, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product , class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-link"  %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <% @categories.each do |category| %>
    <div class="col-md-3 text-center">
      <%= link_to "#{category.name} #{category.products.count}", category_path(category), class: "btn btn-success" %>
    </div>
  <% end %>
</div>

<h1>Listing Products</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-3 text-center">
      <div class="thumbnail">
        <%= link_to( image_tag(product.image(:medium)), product_path(product) ) %>
        <div class="caption">
          <p><%= link_to product.title, product_path(product) %></p>
          <p><%= product.price %> fcaf</p>
          <% if (user_signed_in?) && (current_user == product.user) %>
            <%= link_to 'Edit', edit_product_path(product), class: "btn btn-success" %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @product.image(:medium) %>
		</div>
		<% if @product.categories.any? %>
			<% @product.categories.each do |productCategory| %>
				<%= link_to productCategory.name, category_path(productCategory), class: "btn btn-success" %>
			<% end %>
		<% end %>
		<p><%= @product.description %></p>
	</div>
	<div class="col-md-6">
		<h2><%= @product.title %></h2>
		<h4><%= @product.price %> fcfa</h4>
		<h4><%= @product.user.name %></h4>
		<p><%= link_to 'All user products', user_path(@product.user) %></p>
	</div>
</div>
		
<% if (user_signed_in?) && (current_user == @product.user) %>
	<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-success" %>
	<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
<% end %>
	<%= link_to 'Back', products_path, class: "btn btn-success" %>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.name %>'s products</h1>

<div class="row">
  <% @user_products.each do |product| %>
    <div class="col-md-8 panel panel-default col-md-offset-2">
      <div class="col-sm-4">
        <%= link_to( image_tag(product.image(:medium)), product_path(product) ) %>
      </div>
      <div class="col-sm-6">
        <p><%= link_to product.title, product_path(product) %></p>
        <% if product.categories.any? %>
          <% product.categories.each do |productCategory| %>
            <p><%= link_to productCategory.name, category_path(productCategory) %></p>
          <% end %>
        <% end %>
        <% if (user_signed_in?) && (current_user == product.user) %>
          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-success" %>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
        <% end %>
      </div>
      <div class="col-sm-2">
        <p><%= product.price %> fcaf</p>
      </div>
    </div>
  <% end %>
</div>